### PR TITLE
Expose metadata_link for binary assets

### LINKED ISSUE #235: Make configure_arguments available in the API
See https://github.com/AdoptOpenJDK/openjdk-build/issues/11

This may also be an api issue but we are now adding the bash configure output to the metadata from the builds. Assuming this will now automatically appear in the API, please provide this output on the download so users who are curious can see how exactly our binaries are built

### PR DESCRIPTION
**Pull request by nickebbitt**
Identifies `.json` assets for an archive (.tar.gz, .zip) and exposes against the Package as a metadata_link.

Fixes #235 and #236 

# Checklist

- [x] You added tests to cover the change
- [x] `mvn clean install` build and test completes

### CODE REVIEW

**Comment by nickebbitt** [comment]
I'm unsure about where installers fit? This PR covers package metadata (i.e. .tar.gz, .zip) but not installer metadata (.msi).

**Comment by nickebbitt** [comment]
@johnoliver I've updated this PR, one thing I've done is taken the opportunity to do some minor refactoring, mainly around naming to remove ambiguity between GitHub assets and Adopt assets during mapping. I also added some explicit types where it wasn't obvious e..g Maps of Maps/Lists.

One challenge I had while testing this was that there is fairly tight coupling between the mapper classes (e.g. `AdoptBinaryMapper`) and some lower level utilities that perform HTTP calls.

The implications of this are that to test the logic of the class we have to accept the non-determinism and/or inefficiencies of making external calls in our unit tests which feels a bit awkward.

I started to explore a refactor to invert the dependency for `CachedGithubHtmlClient`, allowing it to be overridden with a fake for testing, and had some success but decided it might be a better one to discuss first and possibly pair on.

**Comment by nickebbitt** [comment]
Also realised this PR doesn't cover `UpstreamBinaryMapper`, does that need  the metadata link also?

**Comment by johnoliver** [comment]
@nickebbitt no we dont need meta data for upstream. So is this PR good to go?

**Comment by johnoliver** [comment]
Assuming this pr is ready, looks good. 

I agree if we can come up with a better way to isolate the http client in tests, would be good. I did have a pr I was putting together to try moving us over to Guice dependency injection for this reason, but the PR got very large

**Comment by nickebbitt** [comment]
Thanks for the merge, yeah all was good to go.

**Pull request merged**
