### PR TITLE
FAQ section

### LINKED ISSUE #296: Create a Frequently Asked Questions (FAQ) document
**Is your feature request related to a problem? Please describe.**
It's important that answers to common/frequent questions about the API are easily discoverable. 

Some examples from the recent 11.0.9 release being:
- when will new binary releases be available via the API?
- how can I trigger a full update of the API data manually?

**Describe the solution you'd like**
A top-level markdown document that collates frequent questions and their answers

### PR DESCRIPTION
**Pull request by nickebbitt**
Create the FAQ document.

Not sure whether what I've currently put in there is completely accurate so review would be useful.

Fixes #296

# Checklist

- [x] You changed or added to the documentation

### CODE REVIEW

**Comment by nickebbitt** [comment]
Do we need to link to it from anywhere? Maybe the main README?

**Comment by sxa** [comment]
Thanks for doing this NIck!

We haven't always linked them from the main README.md so for now I personally don't mind either way if it's linked from there or not.

Ref the 24hr thing - I think there is something else that's done on a more frequent basis, so would be good to cover what it is that's done on a more regular basis in the same place :-)

**Review by sxa — COMMENTED** [review]
Thanks for doing this NIck!

We haven't always linked them from the main README.md so for now I personally don't mind either way if it's linked from there or not.

Ref the 24hr thing - I think there is something else that's done on a more frequent basis, so would be good to cover what it is that's done on a more regular basis in the same place :-)

**Comment by karianna** [comment]
Great stuff! Please do add a link from the README :-)

**Comment by nickebbitt** [comment]
> Ref the 24hr thing - I think there is something else that's done on a more frequent basis, so would be good to cover what it is that's done on a more regular basis in the same place :-)

@sxa yeah agreed, I'll do some digging and see if I can clarify the various ways we update the state and the frequency, failing me working it out and I'm sure @johnoliver will be able to clarify

**Comment by nickebbitt** [comment]
@sxa whilst this has been merged I have it on my list to flesh out the detail more fully around the types of scheduled updates that occur and their frequency

**Pull request merged**
