### PR TITLE
ADR2 Branching & release strategy contributing guide updates

### PR DESCRIPTION
**Pull request by nickebbitt**
Updates to the CONTRIBUTING.md guide based on [ADR2](https://github.com/AdoptOpenJDK/openjdk-api-v3/blob/master/docs/adr/0002-branching-and-release-strategy.md) and #284. 

Merging of this PR should be coordinated with the changes to the branches and OpenShift deployment strategy.

# Checklist

- [x] You changed or added to the documentation

### CODE REVIEW

**Comment by johnoliver** [comment]
Created `production` branch in preparation

**Review by karianna — APPROVED** [review]
LGTM

**Comment by karianna** [comment]
I won't merge this until I get the OK from the API team

**Comment by nickebbitt** [comment]
If I understand the current status of this correctly, I think we need to:
1. Merge `staging` into `master` following the latest PR merge
1. Merge `master` into `production` (or recreate `production` branch from `master` if easier as it's not yet been used)
1. Update OpenShift deployment process to point the Staging env at `master`
1. Update OpenShift deployment process to point the Production env at `production`
1. Once happy with everything, delete the `staging` branch

@johnoliver does this sound accurate?

**Comment by johnoliver** [comment]
@nickebbitt yes that is correct. 2 and 4 are done. Will do 3 when once 1 is done

- [ ] Merge staging into master following the latest PR merge
- [ ] Merge master into production (or recreate production branch from master if easier as it's not yet been used)
- [ ] Update OpenShift deployment process to point the Staging env at master
- [ ] Update OpenShift deployment process to point the Production env at production
- [ ] Once happy with everything, delete the staging branch

**Comment by nickebbitt** [comment]
@johnoliver great stuff, thanks

**Comment by johnoliver** [comment]
staging site now runs off master, some merging of staging into master still to be done

**Comment by nickebbitt** [comment]
@johnoliver even though there's still a merge outstanding from staging, is it safe to say that the work for this PR is effectively done and we can merge this now so the docs are up-to-date for new contributors?

**Comment by nickebbitt** [comment]
I believe this one should be good to go following the merge of #297 

cc. @johnoliver

**Comment by johnoliver** [comment]
yup, only outstanding item would be to delete the staging branch

**Pull request merged**
