### PR TITLE
more tests/coverage

### PR DESCRIPTION
**Pull request by gdams**
##### Checklist

- [x] `mvn clean package` build and test completes
- [ ] documentation is changed or added

### CODE REVIEW

**Comment by karianna** [comment]
@gdams 2 failrures

GitHubAuthTest.readsTokenFromFile:19 expected:<[foo]> but was:<[stub-token]>
[ERROR]   GitHubAuthTest.readsTokenNullFromFile:29 expected:<null> but was:<stub-token>

**Comment by gdams** [comment]
@johnoliver any idea about the failure?

**Comment by karianna** [comment]
@gdams  - GitHubAuthTest.readsTokenNullFromFile:31 expected:<null> but was:<>

**Comment by karianna** [comment]
Fun :-)

```
[ERROR] /home/runner/work/openjdk-api-v3/openjdk-api-v3/adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/BinaryPathTest.kt: (68, 5) Conflicting overloads: public final fun latestDoesRedirectToBinary(): Unit defined in net.adoptopenjdk.api.BinaryPathTest, public final fun latestDoesRedirectToBinary(): Unit defined in net.adoptopenjdk.api.BinaryPathTest
[ERROR] /home/runner/work/openjdk-api-v3/openjdk-api-v3/adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/BinaryPathTest.kt: (77, 5) Conflicting overloads: public final fun latestDoesRedirectToBinary(): Unit defined in net.adoptopenjdk.api.BinaryPathTest, public final fun latestDoesRedirectToBinary(): Unit defined in net.adoptopenjdk.api.BinaryPathTest
```

**Pull request merged**
