### PR TITLE
Code of Conduct for contributors #291

### PR DESCRIPTION
**Pull request by sachinp97**
# Checklist

- [ ] You added tests to cover the change
- [ x] `mvn clean install` build and test completes
- [ x] You changed or added to the documentation

### CODE REVIEW

**Comment by sachinp97** [comment]
Please review

**Comment by karianna** [comment]
I think we have to simply refer to https://www.eclipse.org/org/documents/Community_Code_of_Conduct.php now.

**Review by karianna — CHANGES_REQUESTED** [review]
I think we have to simply refer to https://www.eclipse.org/org/documents/Community_Code_of_Conduct.php now.

**Comment by sachinp97** [comment]
Sure, I just updated it, please review and approve the PR.

**Review by karianna — APPROVED** [review]
LGTM

**Pull request merged**
